sim/mahasiswa/routes.py
from flask import Flask, render_template, redirect, url_for, Blueprint, flash, request
from sim.mahasiswa.forms import mahasiswa_F, loginmahasiswa_F, editmahasiswa_F, pengaduan_F, editpengaduan_F
from sim.models import Tmahasiswa, Tpengaduan
from sim import db, bcrypt
from flask_login import login_user, current_user, logout_user, login_required
import os
import secrets
from sim import app
from PIL import Image

rmahasiswa= Blueprint('rmahasiswa',__name__)

@rmahasiswa.route("/")
def home():
    return render_template("home.html")

@rmahasiswa.route("/about")
def about():
    return render_template("about.html")

@rmahasiswa.route("/data_mahasiswa", methods=['GET', 'POST'])
def data_m():
    form=mahasiswa_F()
    if form.validate_on_submit():
        pass_hass=bcrypt.generate_password_hash(form.password.data).decode('UTF-8')
        add_mahasiswa=Tmahasiswa(npm=form.npm.data, nama=form.nama.data, email=form.email.data, 
        password=pass_hass, kelas=form.kelas.data, alamat=form.alamat.data)
        db.session.add(add_mahasiswa)
        db.session.commit()

        flash(f'Akun- {form.npm.data} berhasil daftar','warning')
        return redirect(url_for('rmahasiswa.login_mahasiswa'))
    return render_template("data-mahasiswa.html", form=form)

@rmahasiswa.route("/login_mahasiswa", methods=['GET', 'POST'])
def login_mahasiswa():
    if current_user.is_authenticated:
        return redirect(url_for('rmahasiswa.home'))
    form=loginmahasiswa_F()
    if form.validate_on_submit():
        ceknpm= Tmahasiswa.query.filter_by(npm=form.npm.data).first()
        if ceknpm and bcrypt.check_password_hash(ceknpm.password, form.password.data):
            login_user(ceknpm)
            flash('Selamat Datang Kembali', 'warning')
            return redirect(url_for('rmahasiswa.akunmahasiswa'))
        else:
            flash('Login Gagal, Periksa NPM dan Password Kembali', 'danger')
    return render_template("login_mahasiswa.html", form=form)

@rmahasiswa.route("/akunmahasiswa")
@login_required
def akunmahasiswa():
    return render_template('akunmahasiswa.html')

@rmahasiswa.route("/logout_mahasiswa")
def logout_mahasiswa():
    logout_user()
    return redirect(url_for('rmahasiswa.home'))

#simpan foto
def simpan_foto(form_foto):
    random_hex= secrets.token_hex(8)
    f_name, f_ext= os.path.splitext(form_foto.filename)
    foto_fn= random_hex + f_ext
    foto_path= os.path.join(app.root_path, 'sim/static/foto', foto_fn)
    ubah_size=(300,300)
    j=Image.open(form_foto)
    j.thumbnail(ubah_size)
    j.save(foto_path)
    #form_foto.save(foto_path)
    return foto_fn

@rmahasiswa.route("/edit_mahasiswa", methods=['GET', 'POST'])
@login_required
def edit_mahasiswa():
    form=editmahasiswa_F()
    if form.validate_on_submit():
        if form.foto.data:
            file_foto=simpan_foto(form.foto.data)
            current_user.foto = file_foto
        pass_hass=bcrypt.generate_password_hash(form.password.data).decode('UTF-8')
        current_user.npm=form.npm.data
        current_user.nama=form.nama.data
        current_user.email=form.email.data
        current_user.kelas=form.kelas.data
        current_user.alamat=form.alamat.data
        current_user.password=pass_hass
        db.session.commit()
        flash('Data berhasil di ubah', 'warning')
        return redirect(url_for('rmahasiswa.edit_mahasiswa'))
    elif request.method=="GET":
        form.npm.data=current_user.npm
        form.nama.data=current_user.nama
        form.email.data=current_user.email
        form.kelas.data=current_user.kelas
        form.alamat.data=current_user.alamat
    return render_template('edit_mahasiswa.html', form=form)

@rmahasiswa.route("/pengaduan", methods=['GET', 'POST'])
@login_required
def pengaduan():
    dt_pengaduan=Tpengaduan.query.filter_by(mahasiswa_id=current_user.id)
    form=pengaduan_F()
    if form.validate_on_submit():
        #tambah data pengaduan
        add_pengaduan= Tpengaduan(subjek=form.subjek.data, kategori=form.kategori.data, detail_pengaduan=form.detail_pengaduan.data, mahasiswa=current_user)
        db.session.add(add_pengaduan)
        db.session.commit()
        flash('Data berhasil ditambahkan', 'warning')
        return redirect(url_for('rmahasiswa.pengaduan'))
    return render_template('pengaduan.html', form=form, dt_pengaduan=dt_pengaduan)

@rmahasiswa.route("/pengaduan/<int:ed_id>/update", methods=['GET', 'POST'])
@login_required
def update_pengaduan(ed_id):
    form=editpengaduan_F()
    dt_pengaduan=Tpengaduan.query.get_or_404(ed_id)
    if request.method=="GET":
        form.subjek.data=dt_pengaduan.subjek
        form.kategori.data=dt_pengaduan.kategori
        form.detail_pengaduan.data=dt_pengaduan.detail_pengaduan
    elif form.validate_on_submit():
        dt_pengaduan.subjek=form.subjek.data
        dt_pengaduan.kategori=form.kategori.data
        dt_pengaduan.detail_pengaduan=form.detail_pengaduan.data
        db.session.commit()
        flash('Data berhasil diubah','warning')
        return redirect(url_for('rmahasiswa.pengaduan'))
    return render_template('editpengaduan.html', form=form)

@rmahasiswa.route("/delete/<id>", methods=['GET', 'POST'])
@login_required
def hapus_pengaduan(id):
    h_pengaduan= Tpengaduan.query.get(id)
    db.session.delete(h_pengaduan)
    db.session.commit()
    flash('Data berhasil di hapus','warning')
    return redirect(url_for('rmahasiswa.pengaduan'))

@rmahasiswa.route("/pengaduan/<int:ed_id>/detail", methods=['GET', 'POST'])
@login_required
def detail_pengaduan(ed_id):
    dt_pengaduan=Tpengaduan.query.get_or_404(ed_id)
    return render_template('detail_pengaduan.html', dt_pengaduan=dt_pengaduan)

@rmahasiswa.route("/artikel/<info>",)
def artikel_info(info):
    return"halaman artikel " + info

sim/templates/about.html
{% extends "base.html"%}

{% block konten%}

<html>
    <head>
        <title>SELAMAT DATANG</title>
    </head>
    
    <body>
        <h1>Selamat datang di website kami</h1>
        <p>Nama : M. Al'Aidin Mutalib</p>
        <P>NPM : 121055520118022</P>
        <p>Kelas : INFO 1</p>
    </body>

</html>
{% endblock%}

sim/templates/akunmahasiswa.html
{% extends "base.html"%}

{% block konten%}

<div class="jumbotron">

    <h1 class="display-4">Hello, {{current_user.nama}}</h1>
    <p class="lead">Selamat Datang di Sistem Informasi Pengaduan. Semoga segala pengaduan anda menjadi perbaikan kami</p>
    <hr class="my-4">
    <p>klik untuk memulai pengaduan anda</p>
    <a class="btn btn-warning btn-lg" href="{{ url_for ('rmahasiswa.pengaduan')}}" role="button">Pengaduan</a>
</div>

{% endblock%}

sim/templates/base.html
<html>
    <head>
        <title>SELAMAT DATANG</title>
        <link rel="stylesheet" href="{{ url_for ('static', filename="css/bootstrap.min.css")}}" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{{ url_for ('static', filename="css/style.css")}}">
    </head>
    
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-warning">
        <div class="container">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{{ url_for ('rmahasiswa.home')}}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for ('rmahasiswa.about')}}">About</a>
                </li>
                {% if current_user.is_authenticated %}

                {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for ('rmahasiswa.login_mahasiswa')}}">Login Mahasiswa</a>
                </li>
                {% endif %}

              </ul>
              <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form>
            </div>
            </div>
          </nav>

       <div class="container mt-4">
           <div class="row">
               <div class="col-md-8">
                <div class="shadow p-3 mb-5 bg-white rounded">
                    <!--falsh-->
                    {% with messages= get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                    {% for category, massage in messages %}

                    <div class="alert alert-{{category}}">
                            {{massage}}
                    </div>
                    {% endfor %}
                    {% endif %}
                    {% endwith %}

                {% block konten%}

                {% endblock%}
                </div>

               </div>

               <div class="col-md-4">
                <div class="shadow p-3 mb-5 bg-white rounded">
                  
                    {% if current_user.is_authenticated %}
                    <div class="card" style="width: 20rem;">
                      <img src="{{url_for('static', filename='foto/' + current_user.foto)}}" class="card-img-top" alt="...">
                      <div class="card-body">
                        <h5 class="card-title">{{current_user.nama}}</h5>
                        <p class="card-text">{{current_user.email}}</p>
                      </div>
                      <ul class="list-group list-group-flush">
                        <li class="list-group-item"><a href="{{url_for('rmahasiswa.akunmahasiswa')}}">Dashboard</a></li>
                        <li class="list-group-item"><a href="{{url_for ('rmahasiswa.pengaduan')}}">Pengaduan</a></li>
                        <li class="list-group-item">Vestibulum at eros</li>
                      </ul>
                      <div class="card-body">
                        <a href="{{url_for('rmahasiswa.edit_mahasiswa')}}" class="card-link">Update Profile</a>
                        <a href="{{url_for('rmahasiswa.logout_mahasiswa')}}" class="card-link">Logout</a>
                      </div>
                    </div>
                   
                    {% else %}
                    <h1>Menu Lain</h1>
                    <li>Data Mahasiswa</li>
                    <li>Data Dosen</li>
                    {% endif %}

               </div>
               </div>
            </div>
       </div>
    </body>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="{{ url_for ('static', filename="js/bootstrap.min.js")}}" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</html>

sim/templates/data-mahasiswa.html
{% extends "base.html"%}

{% block konten%}
<h1>Daftar Akun</h1>
<form method="POST">
          {{form.hidden_tag()}}
    <div class="form-group">
        {{form.npm.label(class="form-control-label")}}
        {% if form.npm.errors %}
              {{form.npm(class="form-control is-invalid")}}

              <div class="invalid-feedback">
                  {%for error in form.npm.errors %}
                  <span>{{error}}</span>
                  {% endfor %}
              </div>
          {%else%}
                {{form.npm(class="form-control")}}

          {%endif%}
    </div>

    <div class="form-group">
        {{form.nama.label(class="form-control-label")}}
        {{form.nama(class="form-control")}}
    </div>

    <div class="form-group">
      {{form.email.label(class="form-control-label")}}
        {% if form.email.errors %}
              {{form.email(class="form-control is-invalid")}}

              <div class="invalid-feedback">
                  {%for error in form.email.errors %}
                  <span>{{error}}</span>
                  {% endfor %}
              </div>
          {%else%}
                {{form.email(class="form-control")}}
                
          {%endif%}
    </div>

    <div class="form-group">
      {{form.kelas.label(class="form-control-label")}}
      {{form.kelas(class="form-control")}}
    </div>

    <div class="form-group">
      {{form.alamat.label(class="form-control-label")}}
      {{form.alamat(class="form-control")}}
    </div>

    <div class="form-group">
      {{form.password.label(class="form-control-label")}}
      {% if form.password.errors %}
            {{form.password(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {%for error in form.password.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
        {%else%}
              {{form.password(class="form-control")}}

        {%endif%}
    </div>

    <div class="form-group">
      {{form.konf_pass.label(class="form-control-label")}}
      {% if form.konf_pass.errors %}
            {{form.konf_pass(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {%for error in form.konf_pass.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
        {%else%}
              {{form.konf_pass(class="form-control")}}

        {%endif%}
    </div>

    <div class="form-group">
      {{form.submit(class="btn btn-primary")}}
    </div>
  </form>

{% endblock%}

sim/templates/detail_pengaduan.html
{% extends "base.html" %}

{% block konten%}

<h3>Detail Pengaduan</h3>
<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Well done!</h4>
    <p>Aww yeah, you successfully read this important alert message. This example text is going to run a bit longer so that you can see how spacing within an alert works with this kind of content.</p>
    <hr>
    <p class="mb-0">Whenever you need to, be sure to use margin utilities to keep things nice and tidy.</p>

    <table class="table table-hover">
        <tr>
            <td>NPM</td>
            <td>{{dt_pengaduan.mahasiswa.npm}}</td>
        </tr>
        <tr>
            <td>Nama</td>
            <td>{{dt_pengaduan.mahasiswa.nama}}</td>
        </tr>
        <tr>
            <td>Email</td>
            <td>{{dt_pengaduan.mahasiswa.email}}</td>
        </tr>
        <tr>
            <td>Kelas</td>
            <td>{{dt_pengaduan.mahasiswa.kelas}}</td>
        </tr>
        <tr>
            <td>Alamat</td>
            <td>{{dt_pengaduan.mahasiswa.alamat}}</td>
        </tr>
    </table>
</div>
<div class="alert alert-warning" role="alert">
    <h4 class="alert-heading">Data Pengaduan</h4>
    <p>Aww yeah, you successfully read this important alert message. This example text is going to run a bit longer so that you can see how spacing within an alert works with this kind of content.</p>
    <hr>
    <p class="mb-0">Whenever you need to, be sure to use margin utilities to keep things nice and tidy.</p>

    <table class="table table-hover">
        <tr>
            <td>Tgl Post</td>
            <td>{{dt_pengaduan.tgl_post}}</td>
        </tr>
        <tr>
            <td>Subjek</td>
            <td>{{dt_pengaduan.subjek}}</td>
        </tr>
        <tr>
            <td>Kategori</td>
            <td>{{dt_pengaduan.kategori}}</td>
        </tr>
        <tr>
            <td>Alamat</td>
        </tr>
        <tr>
            <td>{{dt_pengaduan.detail_pengaduan}}</td>
        </tr>
    </Table>
</div>
<a class="btn btn-warning" href="{{url_for('rmahasiswa.pengaduan')}}">Kembali</a>

{% endblock%}

sim/templates/edit_mahasiswa.html
{% extends "base.html"%}

{% block konten%}
<h1>Update Data Profile</h1>
<form method="POST" enctype="multipart/form-data">
          {{form.hidden_tag()}}
    <div class="form-group">
        {{form.npm.label(class="form-control-label")}}
        {% if form.npm.errors %}
              {{form.npm(class="form-control is-invalid")}}

              <div class="invalid-feedback">
                  {%for error in form.npm.errors %}
                  <span>{{error}}</span>
                  {% endfor %}
              </div>
          {%else%}
                {{form.npm(class="form-control")}}

          {%endif%}
    </div>

    <div class="form-group">
        {{form.nama.label(class="form-control-label")}}
        {{form.nama(class="form-control")}}
    </div>

    <div class="form-group">
      {{form.email.label(class="form-control-label")}}
        {% if form.email.errors %}
              {{form.email(class="form-control is-invalid")}}

              <div class="invalid-feedback">
                  {%for error in form.email.errors %}
                  <span>{{error}}</span>
                  {% endfor %}
              </div>
          {%else%}
                {{form.email(class="form-control")}}
                
          {%endif%}
    </div>

    <div class="form-group">
      {{form.kelas.label(class="form-control-label")}}
      {{form.kelas(class="form-control")}}
    </div>

    <div class="form-group">
      {{form.alamat.label(class="form-control-label")}}
      {{form.alamat(class="form-control")}}
    </div>

    <div class="form-group">
      {{form.password.label(class="form-control-label")}}
      {% if form.password.errors %}
            {{form.password(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {%for error in form.password.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
        {%else%}
              {{form.password(class="form-control")}}

        {%endif%}
    </div>

    <div class="form-group">
      {{form.konf_pass.label(class="form-control-label")}}
      {% if form.konf_pass.errors %}
            {{form.konf_pass(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {%for error in form.konf_pass.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
        {%else%}
              {{form.konf_pass(class="form-control")}}

        {%endif%}
    </div>

    <div class="form-group">
      {{form.alamat.label(class="form-control-label")}}
      {{form.alamat(class="form-control")}}
    </div>

    <div class="form-group">
      {{form.foto.label(class="form-control-label")}}
      {% if form.foto.errors %}
            {{form.foto(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {%for error in form.foto.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
        {%else%}
              {{form.foto(class="form-control")}}

        {%endif%}
    </div>

    <div class="form-group">
      {{form.submit(class="btn btn-primary")}}
    </div>
  </form>

{% endblock%}

sim/templates/editpengaduan.html
{% extends "base.html"%}

{% block konten%}

<div class="jumbotron">

    <h3>Edit Pengaduan</h3>
    <!--FORM PENGADUAN-->
    <form method="POST">
        {{form.hidden_tag()}}
  <div class="form-group">
      {{form.subjek.label(class="form-control-label")}}
      {% if form.subjek.errors %}
            {{form.subjek(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {%for error in form.subjek.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
        {%else%}
              {{form.subjek(class="form-control")}}

        {%endif%}
  </div>

  <div class="form-group">
    {{form.kategori.label(class="form-control-label")}}
    {% if form.kategori.errors %}
          {{form.kategori(class="form-control is-invalid")}}

          <div class="invalid-feedback">
              {%for error in form.kategori.errors %}
              <span>{{error}}</span>
              {% endfor %}
          </div>
      {%else%}
            {{form.kategori(class="form-control")}}

      {%endif%}
  </div>

  <div class="form-group">
    {{form.detail_pengaduan.label(class="form-control-label")}}
    {% if form.detail_pengaduan.errors %}
        {{form.detail_pengaduan(class="form-control is-invalid")}}

        <div class="invalid-feedback">
            {%for error in form.detail_pengaduan.errors %}
            <span>{{error}}</span>
            {% endfor %}
        </div>
    {%else%}
        {{form.detail_pengaduan(class="form-control")}}
    {%endif%}
  </div>


  <div class="form-group">
    {{form.submit(class="btn btn-warning")}}
    <a class="btn btn-secondary" href="{{url_for('rmahasiswa.pengaduan')}}">Kembali</a>
  </div>
</form>
</div>
{% endblock %}

sim/templates/home.html
{% extends "base.html" %}

{% block konten%}

<div class="jumbotron">
    <h1 class="display-4">Hello, world!</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
</div>

{% endblock%}

sim/templates/login_mahasiswa.html
{% extends "base.html"%}

{% block konten%}
<h1>Login Mahasiswa</h1>
<form method="POST">
          {{form.hidden_tag()}}
    <div class="form-group">
        {{form.npm.label(class="form-control-label")}}
        {% if form.npm.errors %}
              {{form.npm(class="form-control is-invalid")}}

              <div class="invalid-feedback">
                  {%for error in form.npm.errors %}
                  <span>{{error}}</span>
                  {% endfor %}
              </div>
          {%else%}
                {{form.npm(class="form-control")}}

          {%endif%}
    </div>

    <div class="form-group">
      {{form.password.label(class="form-control-label")}}
      {% if form.password.errors %}
            {{form.password(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {%for error in form.password.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
        {%else%}
              {{form.password(class="form-control")}}

        {%endif%}
    </div>

    <div class="form-group">
      {{form.submit(class="btn btn-primary")}}
    </div>

    <span><a href="{{ url_for ('rmahasiswa.data_m')}}">Daftar Akun</a></span>
  </form>

{% endblock%}

sim/templates/pengaduan.html
{% extends "base.html"%}

{% block konten%}

<div class="jumbotron">

    <h3>Pengaduan</h3>
    <!--FORM PENGADUAN-->
    <form method="POST">
        {{form.hidden_tag()}}
  <div class="form-group">
      {{form.subjek.label(class="form-control-label")}}
      {% if form.subjek.errors %}
            {{form.subjek(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {%for error in form.subjek.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
        {%else%}
              {{form.subjek(class="form-control")}}

        {%endif%}
  </div>

  <div class="form-group">
    {{form.kategori.label(class="form-control-label")}}
    {% if form.kategori.errors %}
          {{form.kategori(class="form-control is-invalid")}}

          <div class="invalid-feedback">
              {%for error in form.kategori.errors %}
              <span>{{error}}</span>
              {% endfor %}
          </div>
      {%else%}
            {{form.kategori(class="form-control")}}

      {%endif%}
  </div>

  <div class="form-group">
    {{form.detail_pengaduan.label(class="form-control-label")}}
    {% if form.detail_pengaduan.errors %}
        {{form.detail_pengaduan(class="form-control is-invalid")}}

        <div class="invalid-feedback">
            {%for error in form.detail_pengaduan.errors %}
            <span>{{error}}</span>
            {% endfor %}
        </div>
    {%else%}
        {{form.detail_pengaduan(class="form-control")}}
    {%endif%}
  </div>


  <div class="form-group">
    {{form.submit(class="btn btn-primary")}}
  </div>
</form>

<script>
    function klik_hapus(value){
          let valid_link = document.getElementById('del-hapus')
          valid_link.href="/delete/"+ value
    }
</script>
    <hr class="my-4">
    <h4>Data Pengaduan</h4>

    <table class="table table-responsive table-hover">
        <thead>
          <tr>
            <th scope="col">No</th>
            <th scope="col">Tgl</th>
            <th scope="col">Subjek</th>
            <th scope="col">Kategori</th>
            <th scope="col">Edit</th>
            <th scope="col">Hapus</th>
          </tr>
        </thead>
        <tbody>
        {% for data in dt_pengaduan%}
          <tr>
            <th>
              <a href="{{url_for('rmahasiswa.detail_pengaduan', ed_id=data.id)}}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-up-left-square-fill" viewBox="0 0 16 16">
                <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm8.096 10.803L6 6.707v2.768a.5.5 0 0 1-1 0V5.5a.5.5 0 0 1 .5-.5h3.975a.5.5 0 1 1 0 1H6.707l4.096 4.096a.5.5 0 1 1-.707.707z"/>
                </svg>
             </a>
            </th>
            <td>{{data.tgl_post}}</td>
            <td>{{data.subjek}}</td>
            <td>{{data.kategori}}</td>
            <td><a class="btn btn-outline-warning" href="{{url_for('rmahasiswa.update_pengaduan', ed_id=data.id)}}">Edit</a></td>
            <td><a class="btn btn-outline-danger" data-toggle="modal" data-target=#modals-hapus onclick="klik_hapus({{data.id}})">Hapus</a></td>
          </tr>
        {% endfor %}
        <div class="modal" tabindex="-1" role="dialog" id=modals-hapus>
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Konfirmasi hapus</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p>Apakah anda yakin menghapus data ini.</p>
              </div>
              <div class="modal-footer">
                <form action="">
                    <a class="btn btn-warning" id="del-hapus">Hapus</a>
                </form>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>

        </tbody>
      </table>
</div>

{% endblock%}